export const dataSourceSheetColumns = {
  REQUIREMENT: {
    CRM_Product_ID: 0,
    CRM_Product_name: 1,
    Markdown_ID: 2,
    Markdown_Name: 3,
    Qty: 4,
    STATUS_Buffer: 5,
  },
  FACT: {
    Factory_ID: 0,
    Oper_ID: 1,
    Oper_Name: 2,
    Stock_ID: 3,
    Stock_Name: 4,
    Semifinished_ID: 5,
    Semifinished_name: 6,
    Markdown_ID: 7,
    Markdown_name: 8,
    Qty: 9,
  },
  OPERATIONS: {
    Factory_ID: 0,
    Oper_ID: 1,
    Oper_Name: 2,
    Stock_ID: 3,
    Stock_Name: 4,
    Semifinished_ID: 5,
    Semifinished_name: 6,
    Markdown_ID: 7,
    Markdown_name: 8,
  },
  ROUTS: {
    Product_CRM_ID: 0,
    Product_CRM_name: 1,
    Markdown_ID: 2,
    Markdown_Name: 3,
    Oper_ID: 4,
    Oper_Name: 5,
    Semifinished_ID: 6,
    Semifinished_name: 7,
    Semifinished_Markdown_ID: 8,
    Semifinished_Markdown_Name: 9,
    CS_Probability: 10,
  },
};
